### ISSUE TITLE
OpenMeetings Service failed and no response was returned

### ISSUE THREAD

**Issue by sen4ik** [openmeetings/openmeetings-moodle-plugin#14]
Hi

I have Moodle 3.1+ (Build: 20160603) installed with OpenMeetings plugin 2.0.0.4 (2016052401).
I have OpenMeetings server running Apache Openmeetings 3.1.1.

When I am trying to use OpenMeetings inside Moodle i get following error:
array ( 'url' => 'http://myipgoeshere:5080/openmeetings/services/user/login?&user=myuser&pass=mypass', 'content_type' => NULL, 'http_code' => 0, 'header_size' => 0, 'request_size' => 0, 'filetime' => -1, 'ssl_verify_result' => 0, 'redirect_count' => 0, 'total_time' => 0, 'namelookup_time' => 0.00025700000000000001, 'connect_time' => 0, 'pretransfer_time' => 0, 'size_upload' => 0, 'size_download' => 0, 'speed_download' => 0, 'speed_upload' => 0, 'download_content_length' => -1, 'upload_content_length' => -1, 'starttransfer_time' => 0, 'redirect_time' => 0, 'redirect_url' => '', 'primary_ip' => 'myip', 'certinfo' => array ( ), )
Fault (Service error)
Request OpenMeetings! OpenMeetings Service failed and no response was returned. Additioanl info: 

![2016-06-06 12_48_46-editing openmeetings](https://cloud.githubusercontent.com/assets/6224852/15838753/a9473784-2bf4-11e6-8bb2-15084c7b31dd.png)

**Comment by sen4ik** [comment]
If i will hit url http://myipgoeshere:5080/openmeetings/services/user/login?&user=myuser&pass=mypass in the browser, i will get response: {"serviceResult":{"code":1,"message":"da2b236696b150b934826b14f5421f46","type":"SUCCESS"}}
which looks like legit response.

**Comment by solomax** [comment]
Maybe your Moodle web server configured to not be able to performed external requests?
Or maybe port 5080 is not accessible form your Moodle server?

**Comment by sen4ik** [comment]
Oh, i am so sorry, i forgot to reply.
The server was closed on port 5080 for outgoing traffic. Opening port solved the problem.
