### ISSUE TITLE
add start/end time to openmeetings session 

### ISSUE THREAD

**Issue by AshrafHefny** [openmeetings/openmeetings-moodle-plugin#18]
Why there is no option to set start/end time for openmeetings session ? and how can I set this value ?

**Comment by solomax** [comment]
It can be set via config file of OpenMeetings server
https://github.com/apache/openmeetings/blob/3.1.x/openmeetings-web/src/main/webapp/WEB-INF/classes/openmeetings-applicationContext.xml#L114
