### ISSUE TITLE
Moodle vs Openmeetings chat hidden into the room

### ISSUE THREAD

**Issue by cello86** [openmeetings/openmeetings-moodle-plugin#2]
Hi all,
we're testing the Openmeetings 3.0.7 instance with the moodle plugin with success, but we noticed into the rooms created that the user chat is always hidden. Is it possible to maintain opened the chat tab into all the new rooms created by Moodle (with option Chat panel opened by default configurable).?

Thanks,
Marcello

**Comment by solomax** [comment]
fixed!
please check (OM 3.1.0 only :))
