### ISSUE TITLE
Donwload .mp4 button not working on create/edit form 

### ISSUE THREAD

**Issue by carreraj** [openmeetings/openmeetings-moodle-plugin#20]
Add or edit an OpenMeetings resource. Select desired recording. Click on "Download .mp4" button. If the resource has required fields informed it will create/save a room but doesn't download as expected.

Plugin Version; 2.0.2.1
Moodle version: 3.1.4
OpenMeetings version: 3.2.0

**Comment by solomax** [comment]
@moodlebeuth Could you please double-check and publish new release is everything is OK?

**Comment by mwuttke** [comment]
@solomax version 2.0.2.2 is double-checked and released at: https://moodle.org/plugins/pluginversion.php?id=13399

**Comment by solomax** [comment]
Thanks!
