### ISSUE TITLE
Moodle 3.2: update_module_button() has been deprecated

### ISSUE THREAD

**Issue by mwuttke** [openmeetings/openmeetings-moodle-plugin#21]
Hello @solomax ,

When adding an om instance to a moodle 3.2 course using the latest moodle om plugin, I'm seeing that the instance of the openmeetings module is throwing the following errors within the debugging mode: 

> update_module_button() has been deprecated and should not be used anymore. Activity modules should not add the edit module button, the link is already available in the Administration block. Themes can choose to display the link in the buttons row consistently for all module types.
> 
>     line 1129 of /lib/deprecatedlib.php: call to debugging()
>     line 98 of /mod/openmeetings/renderer.php: call to update_module_button()
>     line 120 of /mod/openmeetings/renderer.php: call to mod_openmeetings_renderer->_header()
>     line 381 of /lib/outputrenderers.php: call to mod_openmeetings_renderer->render_openmeetings()
>     line 90 of /mod/openmeetings/view.php: call to plugin_renderer_base->render()

Please could you have a look at the code? 

Here are some links related tor that topic:
[~/mod/upgrade.txt](https://github.com/moodle/moodle/blob/MOODLE_32_STABLE/mod/upgrade.txt)
[https://tracker.moodle.org/browse/MDL-53765](https://tracker.moodle.org/browse/MDL-53765?focusedCommentId=404493&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-404493)

Thanks & Greetings,
Michael

**Comment by solomax** [comment]
hello @moodlebeuth, could you check if issue is fixed for you?

**Comment by mwuttke** [comment]
Hello @solomax ,

now I get the following error message:

```
core_renderer::update_module_button() has been deprecated and should not be used anymore. Activity modules should not add the edit module button, the link is already available in the Administration block. Themes can choose to display the link in the buttons row consistently for all module types.

    line 2651 of /lib/outputrenderers.php: call to debugging()
    line 97 of /mod/openmeetings/renderer.php: call to core_renderer->update_module_button()
    line 119 of /mod/openmeetings/renderer.php: call to mod_openmeetings_renderer->_header()
    line 381 of /lib/outputrenderers.php: call to mod_openmeetings_renderer->render_openmeetings()
    line 90 of /mod/openmeetings/view.php: call to plugin_renderer_base->render()
```

**Comment by solomax** [comment]
Almost the same
Will try another fix

**Comment by solomax** [comment]
@moodlebeuth should be better now :)

**Comment by mwuttke** [comment]
ok, now it works as expected, without any errors. ;-)

Thanks & Greetings,
Michael

**Comment by solomax** [comment]
Thanks for checking!
