### ISSUE TITLE
Exception thrown when show/hide activities in edit mode

### ISSUE THREAD

**Issue by carreraj** [openmeetings/openmeetings-moodle-plugin#22]
Moodle 3.1.5
Plugin 2.0.2.4

When hiding/showing activities in edit mode an ajax call is made. Looks like there is not page context in that case, so an exception is thrown.

Offending line seems to be:  197 of /mod/openmeetings/lib.php: call to format_string()

>diff --git a/mod/openmeetings/lib.php b/mod/openmeetings/lib.php
index b23cb1b..0696425 100644
--- a/mod/openmeetings/lib.php
+++ b/mod/openmeetings/lib.php
@@ -194,7 +194,7 @@ function openmeetings_get_coursemodule_info($coursemodule) {
                return null;
        }
        $info = new cached_cm_info();
\-       $info->name = format_string($meeting->name);
\+       $info->name = $meeting->name;
        $info->onclick = "window.open('" . new moodle_url('/mod/openmeetings/view.php', array ('id' => $coursemodule->id)) .
        return $info;
 }

Removing format_string call fixes it. I've seen core modules doesn't call it in _get_coursemodule_info but I don't know if OM module relies on that call to cleanup the name.

**Comment by solomax** [comment]
Thanks a lot for the detailed report!

Could you please check if `s()` can be used instead of `format_string()` ?
I guess in this case text will be escaped, and there should be no issues

Thanks in advance!

**Comment by carreraj** [comment]
I've tested s() and it doesn't throw the exception so it could be used instead. But I've taken a look to resource and assign modules (core modules) and they don't use any function to clean up the resource name prior to assing it to $info->name. 
So i've created a new OM activity with script tags in the name and checked the database. Tags are stripped and  'test name <script>alert("TEST");</script> of OM room' is saved in the database like 'test name alert("TEST"); of OM room'.
I wouldn't use s(). Is an extra and unnecessary call.

P.S. In OpenMeetings the room name is MOODLE_COURSE_ID_4_NAME_test name alert("TEST"); of OM room

**Comment by solomax** [comment]
Thanks a lot for the investigation!
