### ISSUE TITLE
 OpenMeetings Service failed after change from http to https

### ISSUE THREAD

**Issue by fwsl** [openmeetings/openmeetings-moodle-plugin#24]
Hi,

I've got openmeetings and moodle plugin working on http and wanted to change it to https.
I have followed the instructions on https://openmeetings.apache.org/RTMPSAndHTTPS.html#SSL_for_the_web_interface
for 'Real' certificate, SSL for the web interface, Set up RTMPS and changed openmeetings_port=5443 and  
openmeetings_protocol=https in plugin settings

Openmeetings works as expected thru webgui but does not work thru moodle.
When trying to access room I get error

> array ( 'url' => 'https://IP:5443/openmeetings/services/user/login?&user=LOGIN&pass=PASSWORD', 'content_type' => NULL, 'http_code' => 0, 'header_size' => 0, 'request_size' => 0, 'filetime' => -1, 'ssl_verify_result' => 1, 'redirect_count' => 0, 'total_time' => 0.04322400000000004, 'namelookup_time' => 5.8999999999999998E-5, 'connect_time' => 0.00058600000000000004, 'pretransfer_time' => 0, 'size_upload' => 0, 'size_download' => 0, 'speed_download' => 0, 'speed_upload' => 0, 'download_content_length' => -1, 'upload_content_length' => -1, 'starttransfer_time' => 0, 'redirect_time' => 0, 'redirect_url' => '', 'primary_ip' => 'IP', 'certinfo' => array ( ), 'primary_port' => 5443, 'local_ip' => 'IP', 'local_port' => 49829, )
> Fault (Service error)
> Request OpenMeetings! OpenMeetings Service failed and no response was returned. Additioanl info: 
> Could not login User to OpenMeetings, check your OpenMeetings Module Configuration

Are there some additional steps for this to work?

Cheers 
Grzesiek

**Comment by solomax** [comment]
Can you double check the URL?
I would say URL should be
`https://IP:8443/openmeetings`
and NOT
`https://IP:5443/openmeetings`

**Comment by fwsl** [comment]
Thanks @solomax  
it was not the port, it was the IP.  Until now I had IP and not the hostname in the openmeetings_host setting.
This creates errors as the certificate is issued for the domain name and not the IP.

Thanks again.
Grzesiek
