### ISSUE TITLE
problem in moodle 3.4+ and openmeetings 4

### ISSUE THREAD

**Issue by mikroelektro** [openmeetings/openmeetings-moodle-plugin#26]
I have a server with moodle and openmeetings
Moodle 3.4+
Openmeetings 4
I have installed this plugen and I am not able to get openmeetings to work.
If I Enter wrong username and password in moodle plugin (openmeetings)
I got authentication error .
When having a valid username and password I can see in logs a successful login and a string ( some random latters may be session. Token)
But after that the screen on Moodle is white without any changing.
I have tried 2 different syatems ( ubuntu and centos) as server and I have tested on multiple hosts and still get the same result.
It is not jave or flash problem as I tried many host with the latest update.  I have only tested with moodle 3.4 and moodle 3.4+ as I cant downgrade to moodle 3.3

Thanks alot in advance

**Comment by solomax** [comment]
I only have 3.0.10 right now to test
Will try to set up 3.4 and check what can be wrong

**Comment by solomax** [comment]
Just have installed latest Moodle 3.4
Set up latest available plugin 3.0.0.2 to work with demo-next  (https://om.alteametasoft.com:8443/next)
Works as expected

Maybe you can check what is wrong using Wireshark? (check what is being sent and what is the answer ...)

**Comment by mikroelektro** [comment]
I have tried but it is the same problem. Wireshark wouldnt help as it is https and every thing is encrypted

**Comment by solomax** [comment]
I doubt you can check with demo-next (you need special account for this)
Maybe you can enable Moodle debug and check what errors are you getting?

**Comment by mikroelektro** [comment]
I found the Problem. It was related with the new Firefox as it blocked http content inside of https sites. After ignoring thiw in Firefox or using certificate with OM all works fine.
Thanks for your support and help.

**Comment by solomax** [comment]
Yes HTTPS is required for OpenMeetings
It was announced about a year ago: https://markmail.org/message/c2a3l2vshjqnz5o6
