### ISSUE TITLE
Add global configuration option to disable recording/screensharing.

### ISSUE THREAD

**Issue by fwsl** [openmeetings/openmeetings-moodle-plugin#27]
Hi, 
it would be nice to have option to globally disable recording/screensharing for all current/new instances.
And with that, another one to globally disable "Show recording..." Room type.

Cheers

**Comment by solomax** [comment]
@fwsl 
Partially implemented: https://issues.apache.org/jira/browse/OPENMEETINGS-2562 :))

**Comment by solomax** [comment]
Added option to Moodle plugin config
