### ISSUE TITLE
Cannot download recording or recording is broken

### ISSUE THREAD

**Issue by SubjectXXX** [openmeetings/openmeetings-moodle-plugin#28]
Greetings,

I have managed to record a short screenshare, I renamed it test2.

When I want to download it (from activities settings), its not on the list, while my other recording is (Test1). There is also another recording in dropdown, that I didnt create with this user (it is in My recordings of different user).

If I download any of those two files (Test1 or file I shouldnt see at all), I cannot playback them with any video player.

Also, Download .flv button is missing.

Plugin version 3.0.0.4, Moodle version 3.4.2, OM version 4.0.2

What else can I provide for easier debugging?

![image](https://user-images.githubusercontent.com/2082595/38309586-baf82144-381a-11e8-8360-ae14f4f56ae2.png)

![image](https://user-images.githubusercontent.com/2082595/38309663-da800a22-381a-11e8-9da3-a359327b7edd.png)

**Comment by SubjectXXX** [comment]
Downloaded file that doesnt work..

[flvRecording_2.zip](https://github.com/openmeetings/openmeetings-moodle-plugin/files/1875876/flvRecording_2.zip)

**Comment by solomax** [comment]
Hello @SubjectXXX,

I would love to help
I need very detailed steps to reproduce this issue

Download recordings list is created based on user "external" status (i.e. recording should be created by Moodle user to be downloadable)

flv files are not being created anymore, so "Download as flv" option was removed from Moodle plugin

**Comment by SubjectXXX** [comment]
Sorry for late reply, I went and tested it again with all servers rebooted and caches cleared.

After testing again, fresh recordings now show on a dropdown list for download (that test2 recording is still missing tho..) but when I try to playback it via downloaded file, it doesnt work in vlc or in MPC-HC (Cannot render the file).

It works (playbacks) if I drag and drop it onto whiteboard and press play, just downloaded file seems corrupted..

Hard to do any very detailed steps, since there is not much more detailed description of pressing a recording button, moving mouse a bit, pressing stop button and then after 5 minutes, refreshing page. I guess it has something to do with some settings, in moodle or at server level, but I dont know where and how to start debugging..

**Comment by SubjectXXX** [comment]
Ahh, I see the problem. Downloaded file iz actually gzip file with wrong extension. After renaming to flvRecording_5.zip, extracting file, I get a file without extension. If I add mp4 extension, video playbacks..

Seems plugin problem, right?

**Comment by solomax** [comment]
Need to be investigated ....
What compression options do you have enabled on your web server/in Moodle?

**Comment by SubjectXXX** [comment]
It seems a problem with zlib_compression turned on. If I turn it off, downloaded file is directly watchable with media players..

But its nice to have zlib_compression turned on for other optimizations.. Can plugin be adopted to avoid using zlib_compression?

**Comment by solomax** [comment]
@SubjectXXX this is definitely should be addressed
Could you please tell me how can i turn on `zlib_compression`? Is it Moodle setting?

**Comment by SubjectXXX** [comment]
Its php setting.

Interesting its only me having this problems..

**Comment by solomax** [comment]
Will try to check it.  Thanks for clarifications!

**Comment by solomax** [comment]
Could you please help me?

Please add following code to https://github.com/openmeetings/openmeetings-moodle-plugin/blob/master/mod_form.php#L212

```
if (ini_get_bool('zlib.output_compression')) {
    ini_set('zlib.output_compression', 'Off');
}
```
Would it fix the download?

**Comment by SubjectXXX** [comment]
I added said lines to end of mod_form.php file, turned on zlib.output_compression in php, restarted server and it still doesnt work.

**Comment by solomax** [comment]
Hello @SubjectXXX, can you check if version from `zlib-turn-off` branch works for you? (works for me as expected)

**Comment by solomax** [comment]
@SubjectXXX, Were you able to check?

**Comment by SubjectXXX** [comment]
Hi,

No, I haven't been able to test it, since  I had to switch to another solution for this operations.

Sorry.

Regards, Anze
