### ISSUE TITLE
cannot delete om activity from course/ cannot delete course with om activity

### ISSUE THREAD

**Issue by fwsl** [openmeetings/openmeetings-moodle-plugin#3]
Hello

When trying to delete room from moodle course, there is no error but after refreshing the page, the activity is back.
When trying to delete course containing OM activity I get this: 
`Your call to OpenMeetings Web Services returned an unexpected HTTP status of: 500 Request http://XXX.XXX.XXX.XXX:5080/openmeetings/services/RoomService/deleteRoom?SID=(...)bb2f6db2efc4f&rooms_id=0`

Rooms can be created and accessed without a problem.

plugin version 1.7.5 2015051301
moodle version 2.9.1+ (Build: 20150730)
OM version 3.0.7

UPDATE
The room that cannot be deleted is not accessible, looks like this is a room that was created in older versions of om/om-plugin but was deleted directly through om, or during om update the rooms were not created from backup.
Error while trying to enter room from moodle:
`There is no such room available. The event in the calendar and connected room is already deleted!`

**Comment by solomax** [comment]
ok, this seems to be an issue
if room was deleted in OM directly, Moodle room should be deleted with no issues
will try to address this

**Comment by solomax** [comment]
Not reproducible using latest version (2.0.1)
seems to be fixed :)
please reopen if still an issue
