### ISSUE TITLE
Cannot send persian messages in chat

### ISSUE THREAD

**Issue by mafzalzadeh** [openmeetings/openmeetings-moodle-plugin#31]
Hi.
There is a problem in chat messages with moodle plugin.
When I send a Persian character it responses 500 but English has no problem.
When I go to openmeetings I can send messages with no problem but error happens on moodle and the page goes white and needs to refresh the page.

How can we fix it?

![image](https://user-images.githubusercontent.com/28646692/46909637-90dd1800-cf42-11e8-9a62-ba152c11e649.png)

**Comment by solomax** [comment]
What version of OM are you using?

Am I right thinking your steps are:

1. login room using Moodle (any room type? some specific room options?)
2. open Chat
3. type message in Persian (can you share the message here?)
Result: crash

What in the logs? (openmeetings.log)

**Comment by mafzalzadeh** [comment]
I've found it was because of the MYSQL database collation. It was set on latin1_swedish_ci and when changed it to utf8mb4_persian_ci the problem solved.

Thanks.

**Comment by solomax** [comment]
Good to know :)
