### ISSUE TITLE
openmeetings plugin prevents course backup

### ISSUE THREAD

**Issue by jamc60** [openmeetings/openmeetings-moodle-plugin#34]
Hi
I have installed openmeetings plugin version 4.1.0 and all works well, but the course backup fails when I add plugin to course.
If I execute following command
sudo -u http /usr/bin/php admin/cli/backup.php --courseid=9 --destination=/srv/moodle_courses_backup/
I get following response:

== Performing backup... ==
instantiating backup controller c21a571d0e4593911d4e9614f35d176e
setting controller status to 100
loading controller plan
setting controller status to 300
applying plan defaults
setting controller status to 400
setting file inclusion to 1
checking plan security
setting controller status to 500
setting controller status to 700
saving controller to db
calculating controller checksum 9610cd3712bcef9e0b5683740a7a057b
loading controller from db
setting controller status to 800
Default exception handler: error/cannotfindparentidforelement Debug: 
Error code: cannotfindparentidforelement
$a contents: id
* line 145 of /backup/util/structure/base_final_element.class.php: base_element_struct_exception thrown
* line 326 of /backup/util/structure/backup_nested_element.class.php: call to base_final_element->find_first_parent_by_name()
* line 319 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element->find_element()
* line 214 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element->convert_sql_params()
* line 56 of /mod/openmeetings/backup/moodle2/backup_openmeetings_stepslib.php: call to backup_nested_element->set_source_sql()
* line 88 of /backup/util/plan/backup_structure_step.class.php: call to backup_openmeetings_activity_structure_step->define_structure()
* line 181 of /backup/util/plan/base_task.class.php: call to backup_structure_step->execute()
* line 222 of /backup/moodle2/backup_activity_task.class.php: call to base_task->execute()
* line 178 of /backup/util/plan/base_plan.class.php: call to backup_activity_task->execute()
* line 119 of /backup/util/plan/backup_plan.class.php: call to base_plan->execute()
* line 322 of /backup/controller/backup_controller.class.php: call to backup_plan->execute()
* line 100 of /admin/cli/backup.php: call to backup_controller->execute_plan()

!!! error/cannotfindparentidforelement !!!
!! 
Error code: cannotfindparentidforelement
$a contents: id !!
!! Stack trace: * line 145 of /backup/util/structure/base_final_element.class.php: base_element_struct_exception thrown
* line 326 of /backup/util/structure/backup_nested_element.class.php: call to base_final_element-&gt;find_first_parent_by_name()
* line 319 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element-&gt;find_element()
* line 214 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element-&gt;convert_sql_params()
* line 56 of /mod/openmeetings/backup/moodle2/backup_openmeetings_stepslib.php: call to backup_nested_element-&gt;set_source_sql()
* line 88 of /backup/util/plan/backup_structure_step.class.php: call to backup_openmeetings_activity_structure_step-&gt;define_structure()
* line 181 of /backup/util/plan/base_task.class.php: call to backup_structure_step-&gt;execute()
* line 222 of /backup/moodle2/backup_activity_task.class.php: call to base_task-&gt;execute()
* line 178 of /backup/util/plan/base_plan.class.php: call to backup_activity_task-&gt;execute()
* line 119 of /backup/util/plan/backup_plan.class.php: call to base_plan-&gt;execute()
* line 322 of /backup/controller/backup_controller.class.php: call to backup_plan-&gt;execute()
* line 100 of /admin/cli/backup.php: call to backup_controller-&gt;execute_plan()
 !!

**Comment by jamc60** [comment]
Versions
moodle 3.6.3
openmeetings plugin 4.0.1
openmeetings 4.0.8
php 7.3.4

**Comment by solomax** [comment]
Weird enough everything works for me as expected
Moodle 3.6.1
Will try to update and re-check

**Comment by solomax** [comment]
Did update everything and still no error :(
@jamc60 what am I doing wrong?

**Comment by jamc60** [comment]
Well I do not know. I have reinstalled moodle and I have changed DBMS. Before I used postgresql and now I have used mariadb. The same thing happens as before. If I try to backup a course without the openmeetings module, I get the following:
== Performing backup... ==
instantiating backup controller c0a93ddb4c8734c957d8066ce5c20114
setting controller status to 100
loading controller plan
setting controller status to 300
applying plan defaults
setting controller status to 400
setting file inclusion to 1
checking plan security
setting controller status to 500
setting controller status to 700
saving controller to db
calculating controller checksum c39d6eb474c47c7d913a42d6140075af
loading controller from db
setting controller status to 800
setting controller status to 1000
saving controller to db
Writing /srv/moodle_courses_backup/copia_de_seguridad-moodle2-course-2-test-20190419-1056-nu.mbz
Backup completed.

As soon as I add the openmeetings module, I get the following:
== Performing backup... ==
instantiating backup controller d4e9a77c82fadc47cce3005cfddd01f8
setting controller status to 100
loading controller plan
setting controller status to 300
applying plan defaults
setting controller status to 400
setting file inclusion to 1
checking plan security
setting controller status to 500
setting controller status to 700
saving controller to db
calculating controller checksum c20471c44b8070ceefe76d5d63a2f275
loading controller from db
setting controller status to 800
Default exception handler: error/cannotfindparentidforelement Debug: 
Error code: cannotfindparentidforelement
$a contents: id
* line 145 of /backup/util/structure/base_final_element.class.php: base_element_struct_exception thrown
* line 326 of /backup/util/structure/backup_nested_element.class.php: call to base_final_element->find_first_parent_by_name()
* line 319 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element->find_element()
* line 214 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element->convert_sql_params()
* line 56 of /mod/openmeetings/backup/moodle2/backup_openmeetings_stepslib.php: call to backup_nested_element->set_source_sql()
* line 88 of /backup/util/plan/backup_structure_step.class.php: call to backup_openmeetings_activity_structure_step->define_structure()
* line 181 of /backup/util/plan/base_task.class.php: call to backup_structure_step->execute()
* line 222 of /backup/moodle2/backup_activity_task.class.php: call to base_task->execute()
* line 178 of /backup/util/plan/base_plan.class.php: call to backup_activity_task->execute()
* line 119 of /backup/util/plan/backup_plan.class.php: call to base_plan->execute()
* line 322 of /backup/controller/backup_controller.class.php: call to backup_plan->execute()
* line 100 of /admin/cli/backup.php: call to backup_controller->execute_plan()

!!! error/cannotfindparentidforelement !!!
!! 
Error code: cannotfindparentidforelement
$a contents: id !!
!! Stack trace: * line 145 of /backup/util/structure/base_final_element.class.php: base_element_struct_exception thrown
* line 326 of /backup/util/structure/backup_nested_element.class.php: call to base_final_element-&gt;find_first_parent_by_name()
* line 319 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element-&gt;find_element()
* line 214 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element-&gt;convert_sql_params()
* line 56 of /mod/openmeetings/backup/moodle2/backup_openmeetings_stepslib.php: call to backup_nested_element-&gt;set_source_sql()
* line 88 of /backup/util/plan/backup_structure_step.class.php: call to backup_openmeetings_activity_structure_step-&gt;define_structure()
* line 181 of /backup/util/plan/base_task.class.php: call to backup_structure_step-&gt;execute()
* line 222 of /backup/moodle2/backup_activity_task.class.php: call to base_task-&gt;execute()
* line 178 of /backup/util/plan/base_plan.class.php: call to backup_activity_task-&gt;execute()
* line 119 of /backup/util/plan/backup_plan.class.php: call to base_plan-&gt;execute()
* line 322 of /backup/controller/backup_controller.class.php: call to backup_plan-&gt;execute()
* line 100 of /admin/cli/backup.php: call to backup_controller-&gt;execute_plan()
 !!
Potential coding error - existing temptables found when disposing database. Must be dropped!

I do not know what to try to solve the problem. No other user has this same problem?
