### ISSUE TITLE
Openmeetings version 5 support.

### ISSUE THREAD

**Issue by Aleks-VV** [openmeetings/openmeetings-moodle-plugin#35]
Hello.
When will Openmeetings version 5.0.0-M1 support?
4.0.1 The plugin can not authenticate to Openmeetings 5.0.0-M1 with error:

```
REST call failed
Error While signing into OpenMeetings, please check credentials; message:
Could not login User to OpenMeetings, check your OpenMeetings Module Configuration
```

**Comment by solomax** [comment]
Hello @Aleks-VV,
Moodle plugin works for me as expected
Tested with Moodle 3.6 and demo-next (https://om.alteametasoft.com:8443/next/)

Please ensure 

1. `allow.soap.register` is enabled (https://openmeetings.apache.org/GeneralConfiguration.html)
2. username/password is correct :)

**Comment by samwalther** [comment]
Hello @solomax , 
I am having the same issue. I do have soap enabled, user as external and correct password. I have opened the right ports. My request is hitting the OM server but I do not know how and where to turn on the OM logs. I don't see much info in tomcat access logs. Any tips as to how I debug this further? BTW I am having same issue on localhost where both OM and Moodle are on my localhost on linux.

**Comment by samwalther** [comment]
Here is a screenshot: https://www.screencast.com/t/HPsIo7sb

**Comment by solomax** [comment]
Hello @samwalther,

You have to check openmeetings.log (catalina.out also should have same information)
To be able to perform login call you user *must* have `soap` and `login` rights

Here are the examples: http://openmeetings.apache.org/RestAPISample.html

**Comment by samwalther** [comment]
Even this request is giving 500 server error.
http://localhost:5080/openmeetings/services/UserService?wsdl

That means the web services are probably not working. I have been looking for openmeetings.log but can't find it. Catalina log only has basic access info. 

Do I need to copy some jar file or something to tomcat to make web services work? Any tips for debugging this?

**Comment by Aleks-VV** [comment]
Оn the version OpenMeetings 5.0.0-M1 c88fce9 2019-03-29T14:46:44Z   soap does not work
Getting an error
	HTTP Status 500 – Internal Server Error
Plugin for Moodle does not work.	

On the dev version OpenMeetings 5.0.0-M2-SNAPSHOT 1c16b6d 2019-05-19T13:29:29Z soap works and returns xml answer.
Plugin for Moodle works fine.

Configuration on two installations is the same
3 allow.soap.register true
4 allow.oauth.register true

**Comment by solomax** [comment]
@Aleks-VV just have tested with OM-5.0.0-M1
Everything works as expected under *Java8*
(M1 requires Java8)

M2 requires Java11, and also works as expected
