### ISSUE TITLE
2 moodle 2 different css and logo

### ISSUE THREAD

**Issue by samwalther** [openmeetings/openmeetings-moodle-plugin#37]
We have few different moodle sites which connect to SAME OM 5m1 instance. We would like to find a way so that we can use different branding (colors and logo on top bar in room) for each moodle. Our moodle admin do NOT login to OM admin panel. They just go to room directly from moodle. What would be best way to architect this feature?

Thanks in advance!

**Comment by solomax** [comment]
Good news:
Currently OM has `groups`.
Each group can have different logo

Bad news:
It seems to be unusable for SOAP/REST users

I can suggest you to join user@ mailing list https://openmeetings.apache.org/mailing-lists.html
And start a discussion
I guess this might be doable :)

**Comment by solomax** [comment]
Should be implemented
