### ISSUE TITLE
Error while course backing up Moodle 3.7.1(Build: 20190708) and OM4.0.8

### ISSUE THREAD

**Issue by shtopordm** [openmeetings/openmeetings-moodle-plugin#38]
Hi there I am having difficulty with this plugin...
I am running Moodle 3.7.1(Build: 20190708) with PHP 7.2 and Open Meeting 4.0.8
As a result, I get an error while backing up:

Status - Unfinished
backup_auto_failed_on_course Sandbox
Exception: cannotfindparentidforelement id

When I remove openmeetings from the course, the backup works.

**Comment by solomax** [comment]
Hello @shtopordm,
Unfortunately I'm unable to reproduce the problem :(

Could you share very detailed steps which leads to the error? (I guess steps should include Om activity creation)

Thanks in advance

**Comment by shtopordm** [comment]
Hi @solomax ! I made a backup error report

Debug info: 
Error code: cannotfindparentidforelement
$a contents: id
×Stack trace:
line 145 of /backup/util/structure/base_final_element.class.php: base_element_struct_exception thrown
line 326 of /backup/util/structure/backup_nested_element.class.php: call to base_final_element->find_first_parent_by_name()
line 319 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element->find_element()
line 214 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element->convert_sql_params()
line 56 of /mod/openmeetings/backup/moodle2/backup_openmeetings_stepslib.php: call to backup_nested_element->set_source_sql()
line 88 of /backup/util/plan/backup_structure_step.class.php: call to backup_openmeetings_activity_structure_step->define_structure()
line 181 of /backup/util/plan/base_task.class.php: call to backup_structure_step->execute()
line 222 of /backup/moodle2/backup_activity_task.class.php: call to base_task->execute()
line 178 of /backup/util/plan/base_plan.class.php: call to backup_activity_task->execute()
line 119 of /backup/util/plan/backup_plan.class.php: call to base_plan->execute()
line 337 of /backup/controller/backup_controller.class.php: call to backup_plan->execute()
line 136 of /backup/util/ui/backup_ui.class.php: call to backup_controller->execute_plan()
line 166 of /backup/backup.php: call to backup_ui->execute()

**Comment by shtopordm** [comment]
I do not know how this affects, but OM is located on a separate virtual machine on http. Moodle works on https. 

sorry for my English :)

**Comment by solomax** [comment]
> OM is located on a separate virtual machine on http. Moodle works on https.

I'm afraid this way OM should be unusable due to HHT requests from HTTPS page are usually disabled

Stacktrace gave zero information
I need steps so I can reproduce this issue on my test server :(

**Comment by shtopordm** [comment]
On the server are two virtual machines on Ubuntu 18.04.2. OM is configured on one of the virtual machines, moodle on the other. Used php 7.2. When I start automatic or manual backup, I get an error. If I remove the OM element from the course, then the backup works.  On the test server, the situation repeated

**Comment by shtopordm** [comment]
I assume that the problem is in http-https since when switching to http only automatic backups stop working. The error is the same. Manual backup is normal

**Comment by solomax** [comment]
@shtopordm I see no network related code in backup and was unable to reproduce this issue
Not sure how can help here :(

**Comment by shtopordm** [comment]
the problem is still in the https-http transition. https moodle cannot backup http OM version 4. today I turned the test moodle site back to http and the error completely disappeared, but when ssl was returned for moodle, the error resumed. I will wait for OM5, ssl is initially supported there :) the only question is when will the full release happen :) anyway, thank you for your help!

**Comment by solomax** [comment]
Backup works with local DB
no http/https request are being made

**Comment by shtopordm** [comment]
this is bad because in most cases, these systems are separated

**Comment by solomax** [comment]
OM is not required for Moodle backup

Moodle backup works with local *Moodle* DB only
