### ISSUE TITLE
OM with theme Moove

### ISSUE THREAD

**Issue by what-ri** [openmeetings/openmeetings-moodle-plugin#39]
When adding new activity for OM, the whole course page gets broken with below debug.
Admin does not get the message, only the users.
It has something to do with $participantsitem in the theme. (Participants icon not showing on the left after OM activity added or removed)
If OM activity is removed, the course page stays broken.

line 351 of /theme/moove/lib.php: call to flat_navigation->add()
line 278 of /theme/moove/lib.php: call to theme_moove_rebuildcoursesections()
line 73 of /theme/moove/layout/course.php: call to theme_moove_extend_flat_navigation()
line 1374 of /lib/outputrenderers.php: call to include()
line 1304 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 244 of /course/view.php: call to core_renderer->header()

**Line 351 of the theme: $flatnav->add($coursesections, $participantsitem->key);**

1. Go to Add activity 
2. Click on the course page after OM added

 - OS: Ubuntu 18.0.4
 - Browser chrome
 - OM Version 4.0.5
 - Moodle Version 3.7.2
 - Moodle Plugin Version 4.0.2
- Moodle Theme Moove 3.7.0

Bug has been posted to the theme github as well.

**Comment by what-ri** [comment]
Looks like i manage to sort it out...

Line 4051 in /lib/navigationlib.php
$result = parent::add($node, $beforekey);

I replaced $beforekey with only $key

Debug message is gone, and navbar is not broken anymore...

**Comment by solomax** [comment]
Hello @what-ri,
There is no file `navigationlib.php` in OM Moodle plugin
So I'm not sure how can I fix it :(

**Comment by what-ri** [comment]
Looks like i manage to sort it out...

Line 4051 in /lib/navigationlib.php
$result = parent::add($node, $beforekey);

I replaced $beforekey with only $key

Debug message is gone, and navbar is not broken anymore...

So theme moove with navigation fumbling is not working correctly... Just gonna leave it here as well, maybe someone finds it useful
