### ISSUE TITLE
Delete/backup course with OM

### ISSUE THREAD

**Issue by what-ri** [openmeetings/openmeetings-moodle-plugin#40]
When trying to delete/backup the course, i get the following message only when OM is in the course:

error/cannotfindparentidforelement
Error code: cannotfindparentidforelement
$a contents: id
line 145 of /backup/util/structure/base_final_element.class.php: base_element_struct_exception thrown
line 326 of /backup/util/structure/backup_nested_element.class.php: call to base_final_element->find_first_parent_by_name()
line 319 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element->find_element()
line 214 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element->convert_sql_params()
line 56 of /mod/openmeetings/backup/moodle2/backup_openmeetings_stepslib.php: call to backup_nested_element->set_source_sql()
line 88 of /backup/util/plan/backup_structure_step.class.php: call to backup_openmeetings_activity_structure_step->define_structure()
line 181 of /backup/util/plan/base_task.class.php: call to backup_structure_step->execute()
line 222 of /backup/moodle2/backup_activity_task.class.php: call to base_task->execute()
line 178 of /backup/util/plan/base_plan.class.php: call to backup_activity_task->execute()
line 119 of /backup/util/plan/backup_plan.class.php: call to base_plan->execute()
line 337 of /backup/controller/backup_controller.class.php: call to backup_plan->execute()
line 131 of /admin/tool/recyclebin/classes/category_bin.php: call to backup_controller->execute_plan()
line 185 of /admin/tool/recyclebin/lib.php: call to tool_recyclebin\category_bin->store_item()
line 5030 of /lib/moodlelib.php: call to tool_recyclebin_pre_course_delete()
line 68 of /course/delete.php: call to delete_course()

**To Reproduce**
Insert OM in the course, try to delete or backup the course. 

**Desktop (please complete the following information):**
 - OS: win or android
 - Browser chrome
 - OM Version 4.0.5
 - Moodle Version 3.7. 2
 - Moodle Plugin Version 4.0.5

**Comment by solomax** [comment]
Seems to be duplicate for https://github.com/openmeetings/openmeetings-moodle-plugin/issues/34 and https://github.com/openmeetings/openmeetings-moodle-plugin/issues/38
I'm unable to reproduce this issue :(

Will appreciate any help with finding the steps

**Comment by gdk18985** [comment]
I am facing same issue like **error/cannotfindparentidforelement** when trying to delete a course with OM attached to it.
I have installed OM on same Ubuntu Server which installed Moodle.
One thing to be note that I don't have installed Maria Db, instead i used original Mysql Server installed previously with Moodle Server and only created Database for Open Meetings.
All things are fine except Delete error.

Ubuntu 18.04
Moodle Version 3.7
OM Plugin 4.1.0
OM server version 5.0.0-M4

**Comment by solomax** [comment]
I also using MySql on test system
Can you share very detailed steps to reproduce this issue?
