### ISSUE TITLE
Access denied. You have no rights to enter this room.

### ISSUE THREAD

**Issue by teachermachado** [openmeetings/openmeetings-moodle-plugin#41]
When I click on the Moodle activity and It goes to the Open Meetings it shows the following message:
Access denied. You have no rights to enter this room.

**Comment by solomax** [comment]
Hello @teachermachado 
Please use only one channel to ask questions :)))
(this one was asked 3 times: Moodle plugin forum, github, OM JIRA)

The issue seems to be reproducible I'm going to investigate it

**Comment by solomax** [comment]
Well I just have double-checked everything
And it seems `Access denied` happens only when "Long time ago created room" is used with new integration
i.e. If I'm adding OM activity, then enter the room everything is OK

Can you clarify your configuration and steps?

**Comment by teachermachado** [comment]
I`m creating a new activity and when I click to inside in it it goes to the room and it shows that message. 
My sites uses https but the ip adresss where the OS is there is no https so in my configuration I set https and the door 5443 and I uncheck the two security options. When I try to inside using the recomended configuration the OM didn`t open and lead to a blank page.

**Comment by solomax** [comment]
`When I try to inside using the recomended configuration the OM didnt open and lead to a blank page.` 
This is expected behavior: Om is being displayed inside iframe and the contents is be default being blocked by browser
As workaround you can open OM, confirm you would like to proceed to unsecure site then OM will be opened in iframe

As an alternative you can install free HTTPS certificate (available only if you have domain ...)

**Comment by teachermachado** [comment]
I have a domain www.iutestcenter.com I make a new installation now inside
my website folder not in the VPS but now I am trying to access using
www.iutestcenter.com:5443/online online is the folder were I install Open
Meetings, but is not working it says HTTP STATUS 404 in this domain I have
SSL how do I Access OM using a domain with SSL?

Em qua., 25 de mar. de 2020 às 09:52, Maxim Solodovnik <
notifications@github.com> escreveu:

**Comment by teachermachado** [comment]
I have a domain www.iutestcenter.com I make a new installation now inside my website folder not in the VPS but now I am trying to access using www.iutestcenter.com:5443/online online is the folder were I install Open Meetings, but is not working it says HTTP STATUS 404 in this domain I have SSL how do I Access OM using a domain with SSL?

**Comment by teachermachado** [comment]
Hey, It is open in this address https://iutestcenter.com:5443/openmeetings but it is not opening using the ssl and continues saying not SSL

**Comment by solomax** [comment]
It is not enough to unpack OM to some location
You need to set it up

please check project documentation: https://openmeetings.apache.org/
Before asking check search mailing list archives: https://openmeetings.markmail.org/

We will be happy to answer your questions in user@ mailing list https://openmeetings.apache.org/mailing-lists.html

**Comment by teachermachado** [comment]
I tried to use mailing list but when I send an email it does't work and I receive a outgoing email saying that I can't send email to that adddress

**Comment by teachermachado** [comment]
Do you do paid support? can we talk using emails? machadovar@gmail.com

**Comment by solomax** [comment]
We got increased traffic at user@ mailing list
So it seems to work for most of users

Yes we do commercial support https://openmeetings.apache.org/commercial-support.html
You can contact our manager http://www.unipro.ru/eng/index.html

**Comment by teachermachado** [comment]
Hi. This is the qmail-send program at apache.org.
I'm afraid I wasn't able to deliver your message to the following addresses.
This is a permanent error; I've given up. Sorry it didn't work out.

<user@openmeetings.apache.org>:
Must be sent from an @apache.org address or a subscriber address or an address in LDAP.

--- Below this line is a copy of the message.

**Comment by teachermachado** [comment]
Hi, 

I check the 8888 port and the user and it all set correctly. 
So what can I do now? When I stop KMS the webcam doesn't work. So when I start ir again the cam start to work again, the only problem is the record. 

att

**Comment by teachermachado** [comment]
> It is not enough to unpack OM to some location
> You need to set it up
> 
> please check project documentation: https://openmeetings.apache.org/
> Before asking check search mailing list archives: https://openmeetings.markmail.org/
> 
> We will be happy to answer your questions in user@ mailing list https://openmeetings.apache.org/mailing-lists.html

I already set in this adress https://www.iutestcenter.com:5443/openmeetings but the ssl is not working, but it is a problem to resolve later I resolve the record one.

**Comment by solomax** [comment]
The issue occurs only while 2 browser tabs are opened with different hashes
(due to websession is shared between tabs)

**Comment by njamenconsulting** [comment]
Hello, I want to use openmeeting into moodle; this is issue 
![image](https://user-images.githubusercontent.com/65165423/81554379-94cf5700-937e-11ea-8c01-09847a621fb7.png)

**Comment by njamenconsulting** [comment]
please help me

**Comment by solomax** [comment]
@njamenconsulting please do not `hijack` issues
I believe your issue is caused by wrong URL and/or creadentials to Apache OpenMeetings
Do you have the one installed and configured?

**Comment by njamenconsulting** [comment]
@solomax 
![image](https://user-images.githubusercontent.com/65165423/81591797-e4c91080-93b4-11ea-896c-d9c0ac876b61.png)

**Comment by njamenconsulting** [comment]
this is my configuration ;I leave default setting
