### ISSUE TITLE
Show description in Moodle course

### ISSUE THREAD

**Issue by knedlyk** [openmeetings/openmeetings-moodle-plugin#42]
**Describe the bug**
It is not a bug, only a feature request. Activity "Openmeeting" doesn't have description in Moodle course which is showed to users before they enter the activity (openmeetins session).  
**To Reproduce**
1. Create a course. 
2. Click "Add activity", choose "Openmeetings".
3. Scroll down to 'Comments', fill up the comments frame with some text. 
4. Save the activity. 
5. Comments are not seen neither in the course nor in the openmeetings session

**Expected behavior**
Add a description frame which would be visible below OM session link in the course.

**Screenshots**
Screenshot below shows the Theme with OM session and Assignment, OM doesn't have short description, Assignment has. 
![image](https://user-images.githubusercontent.com/4125496/79036932-76363e80-7bcd-11ea-8bd0-2e9e4840303d.png)

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser: Firefox, Chromium
 - OM Version: 5.0.0.M3
 - Moodle Version: 3.8.0
 - Moodle Plugin Version: 4.0.2 (2019112911)

**Comment by solomax** [comment]
@knedlyk  `comments` are displayed in OM room list (Admin and Rooms section)
will try to add comments to Moodle UI ...
