### ISSUE TITLE
i need help the open meeting does not work

### ISSUE THREAD

**Issue by yplife** [openmeetings/openmeetings-moodle-plugin#43]
the open meeting does not work , it has error

**Comment by solomax** [comment]
it works as expected
no errors

**Comment by yplife** [comment]
please advise

**Comment by yplife** [comment]
nstall plugin from ZIP file
The plugin ZIP package must contain just one directory, named to match the plugin name. The file provided is not a valid plugin ZIP package.

**Comment by solomax** [comment]
Which zip file?

**Comment by yplife** [comment]
the zip file that is here <> code

**Comment by yplife** [comment]
[openmeetings-api-plugin-master (1).zip](https://github.com/openmeetings/openmeetings-moodle-plugin/files/4493927/openmeetings-api-plugin-master.1.zip)

**Comment by solomax** [comment]
this is not Moodle plugin

**Comment by yplife** [comment]
can you please provide moodle plugin , if you can help please

**Comment by solomax** [comment]
sure: https://moodle.org/plugins/mod_openmeetings (download button on the top)

**Comment by yplife** [comment]
error code: when i am trying to create a video call

Array
(
    [url] => http://localhost:5080/openmeetings/services/user/login?&user=admin&pass=password
    [content_type] => 
    [http_code] => 0
    [header_size] => 0
    [request_size] => 0
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.000865
    [namelookup_time] => 0.000635
    [connect_time] => 0
    [pretransfer_time] => 0
    [size_upload] => 0
    [size_download] => 0
    [speed_download] => 0
    [speed_upload] => 0
    [download_content_length] => -1
    [upload_content_length] => -1
    [starttransfer_time] => 0
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 
    [certinfo] => Array
        (
        )

    [primary_port] => 0
    [local_ip] => 
    [local_port] => 0
    [http_version] => 0
    [protocol] => 0
    [ssl_verifyresult] => 0
    [scheme] => 
    [appconnect_time_us] => 0
    [connect_time_us] => 0
    [namelookup_time_us] => 635
    [pretransfer_time_us] => 0
    [redirect_time_us] => 0
    [starttransfer_time_us] => 0
    [total_time_us] => 865
)

**Comment by solomax** [comment]
This plugin will work only AFTER you will install Apache OpenMeetings
It seems you don't have it ...

**Comment by yplife** [comment]
please how to install the easy way

**Comment by yplife** [comment]
https://code.google.com/archive/p/openmeetings/downloads

**Comment by solomax** [comment]
https://cwiki.apache.org/confluence/display/OPENMEETINGS/Tutorials+for+installing+OpenMeetings+and+Tools

**Comment by yplife** [comment]
that is very difficult

**Comment by yplife** [comment]
i just wanted something simple and easy to install and use
