### ISSUE TITLE
Impliment privacy API

### ISSUE THREAD

**Issue by ewallah** [openmeetings/openmeetings-moodle-plugin#45]
The plugin stores the id of the teacher in a database but is **not** GDPR compliant, so unavailable for users from Europe,

**Comment by solomax** [comment]
I would disagree
ID is just a number
there is no way to determine any user details from number

In OM you can `purge` the user and no details will survive

**Comment by ROBERT-MCDOWELL** [comment]
Europe comission is kaput and never been nation representative as their laws are criminal and illegals not respecting the human r ights.

**Comment by ewallah** [comment]
You could still provide a \core_privacy\local\metadata\null_provider to pass at least 

`vendor/bin/phpunit --colors -v "provider_testcase" privacy/tests/provider_test.php`

**Comment by solomax** [comment]
Unfortunately I have no idea what you are talking about :(

**Comment by ewallah** [comment]
- [phpunit](https://docs.moodle.org/dev/PHPUnit)

- [privacy](https://docs.moodle.org/dev/Privacy_API)

**Comment by solomax** [comment]
thanks for the links, but i don't see how is this connected to OM
