### ISSUE TITLE
Issue resolving login into Open Meetings

### ISSUE THREAD

**Issue by Oz-otR** [openmeetings/openmeetings-moodle-plugin#46]
Bug report | Issue resolving login onto Open Meetings Server

I am able to reach the site from an external URL. And using the user login service manually I am returned a SUCCESS. But when I try to add an open meeting activity to moodle. I get a Rest call failure. User has all permissions, Credentials match, Allow.soap.register enabled. Setting user type to external did not work either.  

To Reproduce Steps to reproduce the behavior:

Edit course on moodle
Add an Open Meeting activity
Save and return to course/display 
See error

Expected behavior 
Activity added
Login Successful

OS: Windows 10
Browser Chrome
OM Version 5.00 m4
Moodle Version 3.8.2+
Moodle Plugin Version 4.1.0
Java 11.0.7

![image](https://user-images.githubusercontent.com/32718559/81118594-6f59cd80-8ee6-11ea-9c9f-a9d65e5f9081.png)

![image](https://user-images.githubusercontent.com/32718559/81118513-3e799880-8ee6-11ea-9bb5-d91542b95998.png)

**Comment by solomax** [comment]
Hello @Oz-otR,
I believe your issue is caused by the fact your OM uses self-signed certificate

to allow REST calls in Moodle please **disable** both _Check SSL certificate_ and _Hostname verification_ in plugin settings

later on your users might still have troubles accessing OM due to it is impossible to accept invalid certificate in iFrame ....

As ultimate solution i would recommend to install real certificate ...

**Comment by Oz-otR** [comment]
Hi, 
I tried disabling both settings but am still unable to resolve the error. 
Any other suggestions?

**Comment by solomax** [comment]
@Oz-otR 
from what I can see you have tested `user login service manually I am returned a SUCCESS` with browser
Can you check

1. the same request works from server where your Moodle is installed?
2. PHP has no restrictions on calling REST?

**Comment by Oz-otR** [comment]
Sorry for the delayed response, 
The same request works from server where your Moodle is installed?
**-  Yes, request works from Moodle server. Tested with curl command**

PHP has no restrictions on calling REST?
**- PHP version 7.2.24 does not seem to have any Restrictions on REST**

Additionally I have also installed SSL Certificates for both the Open meetings and the Moodle Site

**Comment by solomax** [comment]
Well, in case there are no restrictions - everything should work ...
Not sure how can I help :(
