### ISSUE TITLE
Access denied. You have no rights to enter this room.

### ISSUE THREAD

**Issue by Zlente** [openmeetings/openmeetings-moodle-plugin#48]
**Describe the bug**
After I finished creating an activity as OM in Moodle, it showed a iframe, opened OM but showed 'Access denied. You have no rights to enter this room.'

**To Reproduce**
1. Install Moodle
2. Install OM
3. Create a user in OM, with same usergroup as module key in Moodle, with type 'EXTERNAL', with all rights 'ROOM', 'DASHBOARD', 'ADMIN', 'LOGIN', 'SOAP'
4. Install Moodle OM Plugin and config information (host, port, ......)
5. Create an OM activity

**Desktop:**
 - OS for Moodle: Win 10
 - OS for OM: Ubuntu 18.04 in Vmware Station
 - Browser: chrome
 - OM Version: 5.0.1
 - Moodle Version: 3.9.0
 - Moodle Plugin Version: 4.1.1 (2020080111)

**Additional context**
I tested OM, it could work well using camera and microphone.
May I know the correct configuration for OM and Moodle plugin?

**Comment by solomax** [comment]
Hello @Zlente 

I see 2 possible options here

- you have 2 opened tabs/windows in same browser with OM opened
- this was fixed in https://issues.apache.org/jira/browse/OPENMEETINGS-2465

Could you please double-check using SNAPSHOT from here https://ci-builds.apache.org/job/OpenMeetings/job/openmeetings/
and the only tab/window

Thanks in advance!

**Comment by solomax** [comment]
@Zlente there is one more option:

- OM cookies are not created for security reasons.

to fix this you need to 

1. create `${OM_HOME/webapps/openmeetings/META-INF}` folder and put
2. put this file https://github.com/apache/openmeetings/blob/master/openmeetings-web/src/main/webapp/META-INF/context.xml into `META-INF` folder
3. change `sameSiteCookies="Lax"` to be `sameSiteCookies="none"`
