### ISSUE TITLE
Open "new window" and "full screen" without iframe

### ISSUE THREAD

**Issue by jochenki** [openmeetings/openmeetings-moodle-plugin#5]
I find a problem.
The plugin generate a "new windows" and "full window" as an iframe.
In both case if in the mms.cfg from adobe flash plugin the variable thirdpartystorage=0 is set (in case of IT-Security), the flash-plugin cannot access the AV-Hardware. Is it possible to get the "new window" function with
a new browser window and the url in Browser of the OM-Server?

**Comment by solomax** [comment]
Actually it is possible but will cause lots of confusion:
"OM-server-url" contains hash which can be used only once, so page refresh will not work as expected
