### ISSUE TITLE
Exception : Attempt to asign property "component" on null

### ISSUE THREAD

**Issue by davidCnam** [openmeetings/openmeetings-moodle-plugin#52]
This error occurs when I want to create an activity or I try to access to the new page "Default completion activity". 

 - Moodle Version: 4.3.1
 - Moodle Plugin Version: 4.3.0 (2022122001)

![openmeetings_error](https://github.com/openmeetings/openmeetings-moodle-plugin/assets/147599153/b2466cfc-7a7c-4d0b-a355-96b763e13c0f)

This error targets the variable in the file : "version.php".

To reproduce the bug: I installed the plugin in Moodle. I tried to create a new activity and I tried to access to the "default completion activity" page.

**Comment by solomax** [comment]
Thanks for the detailed steps

I'll try to reproduce/fix this issue ASAP :)

**Comment by solomax** [comment]
@davidCnam hopefully fixed (version `4.4.0` was just uploaded to Moodle.org) :)
