### ISSUE TITLE
Fault (Service error) - Exception : call to a member function get_record() on  null

### ISSUE THREAD

**Issue by davidCnam** [openmeetings/openmeetings-moodle-plugin#54]
**Describe the bug**
When I try to acces to the "Default activity completion" page this error occured. 

**To Reproduce**
1 - Install the latest version of the plugin
2 - Activate the plugin
3 - Go to the page from "Site administration" -> "Courses" -> "Default settings" -> "Default activity completion"

**Expected behavior**
The page must display a form with all activities available like below.
![image](https://github.com/openmeetings/openmeetings-moodle-plugin/assets/147599153/f103b788-b742-40ee-8b11-578f64061109)

**Screenshots**
![image](https://github.com/openmeetings/openmeetings-moodle-plugin/assets/147599153/0ac6496b-a3a9-4644-b238-a2543b95cd5c)

**Desktop (please complete the following information):**
 - OS: [e.g. win11]
 - Browser [e.g. chrome]
 - Moodle Version [e.g. 4.3.1]
 - Moodle Plugin Version [e.g. 4.4.0]

Best regards.

**Comment by solomax** [comment]
@davidCnam I'll try to check ASAP and will report back here :)

**Comment by solomax** [comment]
Should be fixed!
Version `4.4.1` was just published

Thanks for the detailed report!
