### ISSUE TITLE
error frame

### ISSUE THREAD

**Issue by jramirezcolombia** [openmeetings/openmeetings-moodle-plugin#7]
Good Morning

First I introduce myself

I am Juan Carlos

OpenMeetings several times and integrated with Moodle Debian no problem, but I have a problem and do not know how to fix it

Environment

Server
Intel (R) Xeon (R) E5-2620 v3 @ 2.40GHz CPU 12 cores
32 Gb RAM
Debian 8 of 64 Bits
Kernel on x86_64 3.16.0-4-amd64
Mysql version 5.5.47
PHP 5.6.19
Moodle 3.0.3+ (Build: 20160407)
3.1.1 Revision openmeetings 1736485
Mod 2.0.0.0 openmeetings

The problem is that when trying to enter this activity remains Openmeetings loading as shown in the picture

![captura](https://cloud.githubusercontent.com/assets/18535167/14610751/bd76b2be-0554-11e6-9d8f-c0aff395ac6f.png)

Traducir

Si alguien sabe como puedo solucionar este error lo agradezco

Saludos desde Colombia
If anyone knows how I can fix this error I appreciate

Greetings from Colombia

**Comment by solomax** [comment]
Which version of Moodle plugin are you using?

**Comment by jramirezcolombia** [comment]
$plugin->version    = 2015122801;
$plugin->component  = 'mod_openmeetings';
$plugin->maturity   = MATURITY_STABLE;
$plugin->requires   = 2015042400;
$plugin->release    = '2.0.0.0';
$plugin->cron       = 0;
$plugin->om_version = '3.1+';

**Comment by solomax** [comment]
This version should work as expected
Do you have any errors in OM log?

**Comment by jramirezcolombia** [comment]
attached file logs openmeetings

Thank you
[openmeeting log.zip](https://github.com/openmeetings/openmeetings-moodle-plugin/files/224220/openmeeting.log.zip)

**Comment by jramirezcolombia** [comment]
reviewing the file /opt/red5/log/openmeetings.log

I encounter this error

ERROR 04-17 : 31: 57,481 o.a.o.d.d.s.SessiondataDao : 155 [ http- child - 0.0.0.0-5080 -exec -5] - Could not find session to Update

Thank you

**Comment by jramirezcolombia** [comment]
Goodnight

After reviewing the error patiently and found it:

When the room eg created with id 21 Created by SOAP-Gateway is not taking the organization to be published, or that it is moderated by the administrator
Without which no load the room Moodle

By modifying these values in the room created from OpenMeetings it works without problem.

Sorry for my bad English

**Comment by solomax** [comment]
I'll try to reproduce this error (never saw something like this before)

**Comment by jramirezcolombia** [comment]
Thank you that I got crazy
Another strange thing compared to other versions is that when creating the room from moodle loses despite the same name as properties change from the administration of openmeetings rooms.

It may be a bug in openmeetings 3.1.1? pluguin probe because the same version 2015122801 with moodle installed with a openmeetings 3.0 and works well

**Comment by solomax** [comment]
Hm
Moodle plugin for OM 3.0.7 is not compatible with OM 3.1.1 and vice versa
I'll double check 3.1.1 version and will report back

**Comment by jramirezcolombia** [comment]
ok I will download the version 3.3.1 pluguin to prove again and again

**Comment by solomax** [comment]
please check with 
OM 3.1.1 + moodle plugin 2.0.0.1 (2016042001)

**Comment by solomax** [comment]
Closing this issue, please reopen in case it is still reproducible
